### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by gsouf**
Add missing annotation on expect() to make it ide friendly and allow to autocomplete things like  ``expect(true)->toB...``

### CODE REVIEW

**Comment by ckdarby** [comment]
:+1:

**Comment by danielstjules** [comment]
Mind squashing? :) If so I'll merge.

**Comment by gsouf** [comment]
yeah yeah >.<
Github web interface does not provide squashing

**Comment by danielstjules** [comment]
thanks!

**Pull request merged**
